name: Run Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run tests
        env:
          PROXY_USERNAME: ${{ secrets.PROXY_USERNAME }}
          PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
          IPS_JSON: ${{ secrets.IPS_JSON }}
          USER_AGENTS_JSON: ${{ secrets.USER_AGENTS_JSON }}
          CI: true
        run: npx playwright test --project=${{ matrix.browser }} --trace on

      - name: Upload Playwright Test Artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload Playwright Traces
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-traces
          path: test-results
